// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SqlParquetImporter.Database;

namespace SqlParquetImporter.Database.Migrations
{
    [DbContext(typeof(PriceForecastContext))]
    [Migration("20200801165924_initial-schema")]
    partial class initialschema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SqlParquetImporter.Domain.PriceForecast", b =>
                {
                    b.Property<DateTime>("ForecastDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ForecastModel")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Market")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Product")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ForecastedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ForecastDateTime", "ForecastModel", "Market", "Product", "CountryCode");

                    b.ToTable("PriceForecasts");
                });
#pragma warning restore 612, 618
        }
    }
}
